-- AlterTable
ALTER TABLE "public"."Project" ADD COLUMN     "accountable_owner" TEXT,
ADD COLUMN     "bias_status" TEXT,
ADD COLUMN     "bias_tests" TEXT,
ADD COLUMN     "community_reviews" BOOLEAN,
ADD COLUMN     "diversity_steps" TEXT,
ADD COLUMN     "documentation_consumers" TEXT,
ADD COLUMN     "domain_threshold_met" BOOLEAN,
ADD COLUMN     "escalation_route" TEXT,
ADD COLUMN     "explainability_channels" TEXT,
ADD COLUMN     "fairness_definition" TEXT,
ADD COLUMN     "fairness_stakeholders" TEXT,
ADD COLUMN     "key_features" TEXT,
ADD COLUMN     "lifecycle_stage" TEXT,
ADD COLUMN     "lineage_doc_present" BOOLEAN,
ADD COLUMN     "metrics" TEXT,
ADD COLUMN     "model_cards_published" BOOLEAN,
ADD COLUMN     "mttr_target_hours" DOUBLE PRECISION,
ADD COLUMN     "retention_defined" BOOLEAN,
ADD COLUMN     "robustness_above_baseline" BOOLEAN,
ADD COLUMN     "robustness_tests" TEXT,
ADD COLUMN     "safe_mode" TEXT,
ADD COLUMN     "sector" TEXT,
ADD COLUMN     "significant_decision" BOOLEAN,
ADD COLUMN     "validation_score" DOUBLE PRECISION,
ADD COLUMN     "worst_vuln_fix" TEXT;
